<?php
	// Banner Image
	vc_map(array(
		'name' 				=> esc_html__("WD - Instagram Masonry", 'wd_package'),
		'base' 				=> 'wd_instagram_masonry',
		'description' 		=> esc_html__("WD Instagram", 'wd_package'),
		'category' 			=> esc_html__("WD - Content", 'wd_package'),
		'icon'        		=> 'vc_icon-vc-gitem-image',
		"params" 			=> array(
			/*-----------------------------------------------------------------------------------
				SETTING
			-------------------------------------------------------------------------------------*/
			array(
				"type" 			=> "textfield",
				"class" 		=> "",
				"heading" 		=> esc_html__("Username ID", 'wd_package'),
				"param_name" 	=> "insta_user",
				"description" 	=> sprintf(__('<a href="%s" target="_blank">Get instagram user id by username</a>', 'wd_package'), 'https://smashballoon.com/instagram-feed/find-instagram-user-id/'),
				"value"			=> '1281458368',
				"group"			=> esc_html__('Instagram Setting', 'wd_package'),
			),
			array(
				"type" 			=> "textfield",
				"class" 		=> "",
				"heading" 		=> esc_html__("Client ID", 'wd_package'),
				"param_name" 	=> "insta_client_id",
				"description" 	=> sprintf(__('<a href="%s" target="_blank">How to get client id?</a>', 'wd_package'), 'https://elfsight.com/blog/2016/05/how-to-get-instagram-access-token/'),
				"group"			=> esc_html__('Instagram Setting', 'wd_package'),
				"value"			=> '1eb89899d9214a3ea4473cd5729ba4b4',
				'edit_field_class' => 'vc_col-sm-6',
			),
			array(
				"type" 			=> "textfield",
				"class" 		=> "",
				"heading" 		=> esc_html__("Access Token", 'wd_package'),
				"param_name" 	=> "insta_access_token",
				"description" 	=> sprintf(__('<a href="%s" target="_blank">How to get Access Token?</a>', 'wd_package'), 'https://elfsight.com/blog/2016/05/how-to-get-instagram-access-token/'),
				"group"			=> esc_html__('Instagram Setting', 'wd_package'),
				"value"			=> '5572885065.1eb8989.acee51207b0b44ebbb2ecf0bb337e2b5',
				'edit_field_class' => 'vc_col-sm-6',
			),
			array(
				'type' 			=> 'dropdown',
				'heading' 		=> esc_html__( 'Columns', 'wd_package' ),
				'param_name' 	=> 'insta_columns',
				'admin_label' 	=> true,
				'value' 		=> wd_vc_get_list_tvgiao_columns(),
				"std"			=> 4,
				'description' 	=> '',
				"group"			=> esc_html__('Instagram Setting', 'wd_package'),
				'edit_field_class' => 'vc_col-sm-6',
			),
			array(
				'type' 				=> 'dropdown',
				'heading' 			=> esc_html__( 'Columns On Tablet', 'wd_package' ),
				'param_name' 		=> 'columns_tablet',
				'admin_label' 		=> true,
				'value' 			=> wd_vc_get_list_columns_tablet(),
				'std'				=> 2,
				'description' 		=> esc_html__( '', 'wd_package' ),
				"group"				=> esc_html__('Responsive', 'wd_package'),
			),
			array(
				'type' 				=> 'dropdown',
				'heading' 			=> esc_html__( 'Columns On Mobile', 'wd_package' ),
				'param_name' 		=> 'columns_mobile',
				'admin_label' 		=> true,
				'value' 			=> wd_vc_get_list_columns_mobile(),
				'std'				=> 1,
				'description' 		=> esc_html__( '', 'wd_package' ),
				"group"				=> esc_html__('Responsive', 'wd_package'),
			),
			array(
				"type" 			=> "textfield",
				"class" 		=> "",
				"heading" 		=> esc_html__("Number of photos", 'wd_package'),
				"param_name" 	=> "insta_number",
				"value"			=> 4,
				"description" 	=> esc_html__('Max 12 photos', 'wd_package'),
				"group"			=> esc_html__('Instagram Setting', 'wd_package'),
				'edit_field_class' => 'vc_col-sm-6',
			),
			array(
				"type" 			=> "textfield",
				"class" 		=> "",
				"heading" 		=> esc_html__("Padding", 'wd_package'),
				"param_name" 	=> "insta_padding",
				"value"			=> 0,
				"description" 	=> esc_html__('Padding between images. Only fill in whole numbers or real numbers. Example: 2.5 (Unit: pixels)', 'wd_package'),
				"group"			=> esc_html__('Instagram Setting', 'wd_package'),
				'edit_field_class' => 'vc_col-sm-6',
			),
			array(
				"type" 			=> "dropdown",
				"class" 		=> "",
				"heading" 		=> esc_html__("Photo Size", 'wd_package'),
				"admin_label" 	=> true,
				"param_name" 	=> "insta_size",
				"value" 		=> wd_vc_get_list_instagram_image_size(),
				"description" 	=> "",
				"std"			=> 'low_resolution',
				"group"			=> esc_html__('Instagram Setting', 'wd_package'),
				'edit_field_class' => 'vc_col-sm-6',
			),
			array(
				"type" 			=> "dropdown",
				"class" 		=> "",
				"heading" 		=> esc_html__("Sort By", 'wd_package'),
				"admin_label" 	=> true,
				"param_name" 	=> "insta_sortby",
				"value" 		=> wd_vc_get_list_instagram_sort_by(),
				"description" 	=> "",
				"std"			=> 'none',
				"group"			=> esc_html__('Instagram Setting', 'wd_package'),
				'edit_field_class' => 'vc_col-sm-6',
			),
			array(
				"type" 			=> "dropdown",
				"class"			=> "",
				"heading" 		=> esc_html__("Action When Click Item", 'wd_package'),
				"param_name" 	=> "insta_action_click_item",
				"value" 		=> array(
						'Lightbox' 			=> 'lightbox',
						'Instagram Link' 	=> 'link',
					),
				'std'			=> 'lightbox',
				"group"			=> esc_html__('Instagram Setting', 'wd_package'),
				'edit_field_class' => 'vc_col-sm-6',
			),
			array(
				"type" 			=> "dropdown",
				"class"			=> "",
				"heading" 		=> esc_html__("Open links in", 'wd_package'),
				"param_name" 	=> "insta_open_win",
				"value" 		=> wd_vc_get_list_link_target(),
				"group"			=> esc_html__('Instagram Setting', 'wd_package'),
				'edit_field_class' => 'vc_col-sm-6',
				'dependency'  	=> array('element' => "insta_action_click_item", 'value' => array('link')),
			),
			
			array(
				'type' 			=> 'textfield',
				'class' 		=> '',
				'heading' 		=> esc_html__("Mansory Image Size", 'wd_package'),
				'description' 	=> esc_html__("", 'wd_package'),
				'admin_label' 	=> true,
				'param_name' 	=> 'mansory_image_size',
				'value' 		=> '1:1, 1:1, 2:2, 1:1, 1:1, 1:1, 1:1, 1:1, 1:1',
				"group"			=> esc_html__('Instagram Setting', 'wd_package'),
			),
			
			array(
				'type' 			=> 'textfield',
				'class' 		=> '',
				'heading' 		=> esc_html__("Extra class name", 'wd_package'),
				'description'	=> esc_html__("Style particular content element differently - add a class name and refer to it in custom CSS.", 'wd_package'),
				'admin_label' 	=> true,
				'param_name' 	=> 'class',
				'value' 		=> '',
			)
		)
	));
?>